# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa miasta')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Odnośnik')),
            ],
            options={
                'verbose_name_plural': 'Miasta',
                'verbose_name': 'Miasto',
            },
        ),
    ]
