# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Nazwa angielska'),
        ),
    ]
