# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160610_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
