# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nazwa miasta'),
        ),
    ]
